### Server settings (ServerProperties) ###

server:
  port: 8080
  address: localhost
  sessionTimeout: 30
  servlet:
    context-path: /sqtrl

#Custom properties
  
#Tomcat specifics
tomcat:
    accessLogEnabled: false
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs
    
custom:
    endpoint: "http://localhost:3030/HP_0510"
    ruleFile: "validRules.xml"
    maxCost: 7.0